export const IMAGE_NAMES = {
  home: require('../../assets/images/home.png'),
  trackMap: require('../../assets/images/trackMap.png'),
  auth_logo: require('../../assets/images/auth_logo.png'),
  faceBook: require('../../assets/icons/facebook.png'),
  google: require('../../assets/icons/google.png'),
  apple: require('../../assets/icons/apple.png'),
  arrow_left: require('../../assets/images/backArrow.png'),
  dummyProfile: require('../../assets/images/dummy_profile.png'),
  camera: require('../../assets/images/camera.png'),
  welcome: require('../../assets/images/welcome.png'),
  motherDairy: require('../../assets/images/motherDairyIcon.png'),
  phone: require('../../assets/icons/phone.png'),
  mail: require('../../assets/icons/mail.png'),
  lock: require('../../assets/icons/lock.png'),
  dummyGirl: require('../../assets/images/dummyGirl.png'),
  contactUs: require('../../assets/images/contactImg.png'),
  mapLocation: require('../../assets/images/mapLocation.png'),
  clouds: require('../../assets/images/clouds.png'),
  whiteCircle: require('../../assets/images/whiteCircle.png'),
  greenCart: require('../../assets/images/greenCart.png'),
  shopping: require('../../assets/images/shopping.png'),
  shadow: require('../../assets/images/shadow.png'),
  iDummy: require('../../assets/images/dummy.png'),
  groceries: require('../../assets/images/groceries.png'),
  gallery: require('../../assets/images/gallery.png'),
  clock: require('../../assets/images/clock.png'),
  person: require('../../assets/images/person1.png'),
  logo: require('../../assets/images/Group.png'),
  
};
