// export const API_URL: string = 'https://appgrowthcompany.com:1010/api/v1/User/';
// export const API_URL: string =
//   'https://bernardapi.appgrowthcompany.com/api/v1/User/';

export const API_URL: string = 'https://apikoridorr.koridorr.com/api/v1/User/';
export const END_POINTS = {
  signUp: 'signup',
  socialLogin: 'socialLogin',
  login: 'login',
  otp: 'verifyOtp',
  getProfile: 'getProfile',
  forgetPassword: 'forgotPassword',
  profile: 'updateProfile',
  resetPassword: 'resetPassword',
  changePassword: 'changePassword',
  resendOtp: 'sendOtp',
  logout: 'logout',
  getCategory: 'getCategory',
  getSubCategory: 'getSubCategory',
  getBrand: 'getBrand',
  getProduct: 'getProduct',
  getVendor: 'getVendor',
  getCms: 'getCms',
  addAddress: 'addUserAddress',
  getAddress: 'getAddress',
  updatedAddress: 'updatedAddress',
  deleteAddress: 'deleteAddress',
  addToCart: 'addToCart',
  removeCart: 'removeToCart',
  getCart: 'getCart',
  faqs: '',
  addWishlist: 'wishlist',
  getCoupons: 'getCoupons',
  getOrder: 'getOrder',
  placeOrder: 'placeOrder',
  filter: 'filter',
  rating: 'addRating',
  getUserNotification: 'getUserNotification',
  clearNotification: 'clearNotification',
  orderStatus: 'orderStatus',
  addcard: 'addCard',
  getCard: 'getCard',
  deleteCard: 'deleteCard',
  deleteAccount: 'deleteAccount',
  getAllVendors: 'getAllVendor',
  reOrder: 'reOrder',
};
